// <auto-generated />
using System;
using Contexto.Esquema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contexto.Migrations
{
    [DbContext(typeof(Repositorio))]
    [Migration("20200211055615_EntradaDeLogConDetalles")]
    partial class EntradaDeLogConDetalles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Contexto.Entidades.EntradaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Creado");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("Eliminado");

                    b.Property<DateTime>("Modificado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<int>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("EntradaLog");
                });

            modelBuilder.Entity("Contexto.Entidades.EntradaLogDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Creado");

                    b.Property<DateTime?>("Eliminado");

                    b.Property<int>("IdEntradaLog");

                    b.Property<DateTime>("Modificado");

                    b.Property<string>("Valor")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("IdEntradaLog");

                    b.ToTable("EntradaLogDetalle");
                });

            modelBuilder.Entity("Contexto.Entidades.EntradaLogDetalle", b =>
                {
                    b.HasOne("Contexto.Entidades.EntradaLog", "EntradaLog")
                        .WithMany()
                        .HasForeignKey("IdEntradaLog")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
