// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servicio.Contexto;

namespace Servicio.Migrations
{
    [DbContext(typeof(Repositorio))]
    [Migration("20191017020919_TablaUsuarios")]
    partial class TablaUsuarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Servicio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(192);

                    b.Property<DateTime>("Creado");

                    b.Property<DateTime?>("Eliminado");

                    b.Property<DateTime>("Modificado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("NumeroContacto")
                        .IsRequired()
                        .HasMaxLength(18);

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
