// <auto-generated />
using System;
using Contexto.Esquema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contexto.Migraciones
{
  [DbContext(typeof(Repositorio))]
  [Migration("20200219035627_Bitacora")]
  partial class Bitacora
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
          .HasAnnotation("Relational:MaxIdentifierLength", 128)
          .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

      modelBuilder.Entity("Contexto.Entidades.Bitacora", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            b.Property<DateTime>("Creado");

            b.Property<string>("Descripcion")
                      .HasMaxLength(512);

            b.Property<DateTime?>("Eliminado");

            b.Property<DateTime>("Modificado");

            b.Property<string>("Nombre")
                      .IsRequired()
                      .HasMaxLength(128);

            b.Property<int>("Tipo");

            b.HasKey("Id");

            b.HasIndex("Creado", "Modificado");

            b.ToTable("Bitacora");
          });

      modelBuilder.Entity("Contexto.Entidades.BitacoraDetalle", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            b.Property<DateTime>("Creado");

            b.Property<DateTime?>("Eliminado");

            b.Property<long>("IdBitacora");

            b.Property<DateTime>("Modificado");

            b.Property<string>("Valor")
                      .IsRequired();

            b.HasKey("Id");

            b.HasIndex("IdBitacora");

            b.HasIndex("Creado", "Modificado");

            b.ToTable("BitacoraDetalle");
          });

      modelBuilder.Entity("Contexto.Entidades.BitacoraDetalle", b =>
          {
            b.HasOne("Contexto.Entidades.Bitacora", "Bitacora")
                      .WithMany()
                      .HasForeignKey("IdBitacora")
                      .OnDelete(DeleteBehavior.Cascade);
          });
#pragma warning restore 612, 618
    }
  }
}
